package com.dickodb.annotation.descriptors;

public class KeyDescriptor extends AbstractDescriptor{
    private boolean autoGenerated;

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }
}
